project:
  type: website
  output-dir: docs
  
website:
  title: "Haitian Chamber of commerce Great Britain"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/JudeIX/Haitian-chamber-commerce-GB
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Haitian Chamber of commerce Great Britain "

format:
  html:
    theme: cerulean
    toc: true

editor: source

